package com.wcp.equipment.pojo;

import java.util.Date;

public class AlipayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.merchantInfoId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String merchantinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.amount
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.userId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.username
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.trado_no
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String tradoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.buyer_logon_id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String buyerLogonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.seller_email
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.status
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.createTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipayrecord.updateTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.id
     *
     * @return the value of alipayrecord.id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.id
     *
     * @param id the value for alipayrecord.id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.merchantInfoId
     *
     * @return the value of alipayrecord.merchantInfoId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getMerchantinfoid() {
        return merchantinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.merchantInfoId
     *
     * @param merchantinfoid the value for alipayrecord.merchantInfoId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setMerchantinfoid(String merchantinfoid) {
        this.merchantinfoid = merchantinfoid == null ? null : merchantinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.amount
     *
     * @return the value of alipayrecord.amount
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.amount
     *
     * @param amount the value for alipayrecord.amount
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.userId
     *
     * @return the value of alipayrecord.userId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.userId
     *
     * @param userid the value for alipayrecord.userId
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.username
     *
     * @return the value of alipayrecord.username
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.username
     *
     * @param username the value for alipayrecord.username
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.trado_no
     *
     * @return the value of alipayrecord.trado_no
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getTradoNo() {
        return tradoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.trado_no
     *
     * @param tradoNo the value for alipayrecord.trado_no
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setTradoNo(String tradoNo) {
        this.tradoNo = tradoNo == null ? null : tradoNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.buyer_logon_id
     *
     * @return the value of alipayrecord.buyer_logon_id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getBuyerLogonId() {
        return buyerLogonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.buyer_logon_id
     *
     * @param buyerLogonId the value for alipayrecord.buyer_logon_id
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setBuyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId == null ? null : buyerLogonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.seller_email
     *
     * @return the value of alipayrecord.seller_email
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.seller_email
     *
     * @param sellerEmail the value for alipayrecord.seller_email
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.status
     *
     * @return the value of alipayrecord.status
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.status
     *
     * @param status the value for alipayrecord.status
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.createTime
     *
     * @return the value of alipayrecord.createTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.createTime
     *
     * @param createtime the value for alipayrecord.createTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipayrecord.updateTime
     *
     * @return the value of alipayrecord.updateTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipayrecord.updateTime
     *
     * @param updatetime the value for alipayrecord.updateTime
     *
     * @mbggenerated Wed Jan 16 23:56:19 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}