package com.wcp.equipment.pojo;

import java.util.Date;

public class Merchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.app_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.sign
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.notify_url
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.app_auth_token
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String appAuthToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.store_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.merchantPrivateKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String merchantprivatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.alipayPublicKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String alipaypublickey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.equimentId
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private String equimentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.mostTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private Integer mosttimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.successTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private Integer successtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.createTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.updateTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.id
     *
     * @return the value of merchant.id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.id
     *
     * @param id the value for merchant.id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.app_id
     *
     * @return the value of merchant.app_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.app_id
     *
     * @param appId the value for merchant.app_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.sign
     *
     * @return the value of merchant.sign
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.sign
     *
     * @param sign the value for merchant.sign
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.notify_url
     *
     * @return the value of merchant.notify_url
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.notify_url
     *
     * @param notifyUrl the value for merchant.notify_url
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.app_auth_token
     *
     * @return the value of merchant.app_auth_token
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getAppAuthToken() {
        return appAuthToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.app_auth_token
     *
     * @param appAuthToken the value for merchant.app_auth_token
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setAppAuthToken(String appAuthToken) {
        this.appAuthToken = appAuthToken == null ? null : appAuthToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.store_id
     *
     * @return the value of merchant.store_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.store_id
     *
     * @param storeId the value for merchant.store_id
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.merchantPrivateKey
     *
     * @return the value of merchant.merchantPrivateKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getMerchantprivatekey() {
        return merchantprivatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.merchantPrivateKey
     *
     * @param merchantprivatekey the value for merchant.merchantPrivateKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setMerchantprivatekey(String merchantprivatekey) {
        this.merchantprivatekey = merchantprivatekey == null ? null : merchantprivatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.alipayPublicKey
     *
     * @return the value of merchant.alipayPublicKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getAlipaypublickey() {
        return alipaypublickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.alipayPublicKey
     *
     * @param alipaypublickey the value for merchant.alipayPublicKey
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setAlipaypublickey(String alipaypublickey) {
        this.alipaypublickey = alipaypublickey == null ? null : alipaypublickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.equimentId
     *
     * @return the value of merchant.equimentId
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public String getEquimentid() {
        return equimentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.equimentId
     *
     * @param equimentid the value for merchant.equimentId
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setEquimentid(String equimentid) {
        this.equimentid = equimentid == null ? null : equimentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.mostTimes
     *
     * @return the value of merchant.mostTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public Integer getMosttimes() {
        return mosttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.mostTimes
     *
     * @param mosttimes the value for merchant.mostTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setMosttimes(Integer mosttimes) {
        this.mosttimes = mosttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.successTimes
     *
     * @return the value of merchant.successTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public Integer getSuccesstimes() {
        return successtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.successTimes
     *
     * @param successtimes the value for merchant.successTimes
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setSuccesstimes(Integer successtimes) {
        this.successtimes = successtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.createTime
     *
     * @return the value of merchant.createTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.createTime
     *
     * @param createtime the value for merchant.createTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.updateTime
     *
     * @return the value of merchant.updateTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.updateTime
     *
     * @param updatetime the value for merchant.updateTime
     *
     * @mbggenerated Tue Jan 15 20:20:14 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}