package com.wcp.equipment.dao;

import com.wcp.equipment.pojo.MerchantInfo;
import com.wcp.equipment.pojo.MerchantInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int countByExample(MerchantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int deleteByExample(MerchantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int insert(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int insertSelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    List<MerchantInfo> selectByExample(MerchantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    MerchantInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") MerchantInfo record, @Param("example") MerchantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int updateByExample(@Param("record") MerchantInfo record, @Param("example") MerchantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int updateByPrimaryKeySelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantinfo
     *
     * @mbggenerated Tue Jan 15 01:42:24 CST 2019
     */
    int updateByPrimaryKey(MerchantInfo record);
}